# Site settings
title: Botzheim IT Kft.
title_de: Botzheim IT Kft.
email: gabor@botzheim.de
baseurl: "homepage_SWE"
url: https://www.botzheim.de
description: "Portfolio Website"
description_de: "Portfolio Webseite."
keywords: "SW,Development,C++,Java,Qt,Qml,Requirements"
keywords_de: "SW,Entwickung,C++,Java,Qt,Qml,Requirements"
skills: "Software Development - Requirements Engineering - Management"
skills_de: "Software Entwicklung - Requirements Engineering - Management"
about: "About"
about_de: "Über mich"
contact_title: "Contact"
contact_title_de: "Kontakt"
about_me1: "We are Software Engineers, focusing on software development, requirements engineering and management.
          We have gathered the most experience until now in the aerospace industry, both in the civil and the military area.
          We furthermore had noteworthy projects in the automotive, meditech and geodesic industry."
about_me1_de: "Wir sind Software Ingenieure, mit Fokus auf Software-Entwicklung, Requirement Engineering und Management.
          Am meisten Erfahrung konnten wir bis jetzt in der Luft und Raumfahrtbranche sammeln, sowohl im Zivilen und Militärischen Bereich.
          Desweiteren hatten wir noch viele nennenswerte Projekte in der Automobil-, der Medizintechnik- und der Vermessungsbranche."
about_me2: "Our strong side in software development is embedded C++, Java, Qt development with knowledge of numerous frameworks. We are able to work productive both in single or multinational team projects
         and readily bring in and distribute our knowledge. We understand SW and Management side, and can act well as a mediator between the two worlds.
         In requirements engineering, our experience from both perspectives helps to create efficient and good requirements. "
about_me2_de: "In der Software-Entwicklung liegen unsere Stärken bei C++, Java, Qt und diversen Frameworks. Wir arbeiten sowohl einzeln als auch in verteilten Multinationalen Teams produktiv
         und bringen unsere Erfahrung gerne in ein Team ein. Wir können gut als Vermittler zwischen den zwei Welten der SW Entwicklung und Management agieren.
         Beim Requirement Engineering hilft unsere Erfahrung aus beiden Perspektiven bei der Erstellung von effizienten und guten Anforderungen. "
email_send: "Send"
email_send_de: "Senden"
email_address: "Email Address"
email_address_de: "Email-Adresse"
email_message: "Message"
email_message_de: "Nachricht"
email_contact: "Contact Me"
email_contact_de: "Kontaktieren"
meta_author: Botzheim Gabor

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
formspree_id: f/xgebjrza

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: x

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Botzheim IT Kft.
  location: Budapest, Wien
  credits: Credits

# Postal address (add as many lines as necessary)
address:
  - line: Diófa utca 6
  - line: Pilisvörösvár, 2085

# Credits content
credits: <a href="impressum.html">Impressum</a>

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
